GET http://localhost:5000/users

###

GET http://localhost:5000/todos

### 

POST  http://localhost:5000/todos

{
    "content": "..."
    
}

type Todo struct {
	ID         int       `json:"id"`
	Complete   bool      `json:"isComplete"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"createdAt"`
	LastEdited time.Time `json:"lastEdited"`
}